GRAPH_TITLE = 'f(z) = 1/(z+1)'
X_GRID_START = -10.
X_GRID_STOP = 10.
X_GRID_STEP = 1.
Y_GRID_START = -10.
Y_GRID_STOP = 10.
Y_GRID_STEP = 1.
RENDER_SAMPLE_SIZE = 100
IS_THE_IDENTITY_GRID_SHOWN = False
ARE_THE_REAL_CURVES_SHOWN = True
ARE_THE_IMAGINARY_CURVES_SHOWN = True
ALPHA_VALUE = 0.75


def complex_function_formula(z):
    return (1/(z+1))
